class DobBetsapiConstant {
  static PROP_SPORT_VALUE_SCORE = 1;

  static PROP_LANGUAGE_VALUE_EN = 1;
  static PROP_LANGUAGE_VALUE_ZH_CN = 10;

  static PROP_MATCH_STATUS_VALUE_NOT_STARTED = 0;
  static PROP_MATCH_STATUS_VALUE_IN_PLAY = 1;
  static PROP_MATCH_STATUS_VALUE_TO_BE_FIXED = 2;
  static PROP_MATCH_STATUS_VALUE_ENDED = 3;
  static PROP_MATCH_STATUS_VALUE_POSTPONED = 4;
  static PROP_MATCH_STATUS_VALUE_CANCELLED = 5;
  static PROP_MATCH_STATUS_VALUE_WALKOVER = 6;
  static PROP_MATCH_STATUS_VALUE_INTERRUPTED = 7;
  static PROP_MATCH_STATUS_VALUE_ABANDONED = 8;
  static PROP_MATCH_STATUS_VALUE_RETIRED = 9;
  static PROP_MATCH_STATUS_VALUE_SUSPENDED = 10;
  static PROP_MATCH_STATUS_VALUE_DEDIDED_BY_FA = 11;
  static PROP_MATCH_STATUS_VALUE_REMOVED = 99;
}

module.exports = DobBetsapiConstant;